spring:
  application:
    name: heysong
#     主要用于指定 Spring Boot 应用的名称，它在很多场景下有重要作用，比如在服务发现、配置管理等方面，用于标识应用。
#  在微服务架构中，注册到服务中心的服务名通常就是这个配置的值。它并不直接决定应用的访问路径，
#  但会在一些与路径相关的配置或框架集成中有间接影响。在默认情况下，如果没有其他特殊配置，应用的访问路径不会直接包含 spring.application.name 的值。
#  但如果使用了一些网关或路由配置，可能会根据这个名称来构建路由规则等。
  profiles:
    active:
      - dev
      - debug
load:
  property:
    cron: 180000